/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;


import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Imei1;
import model.Product;
import model.ProductDetails;
import repository.CPUDAO;
import repository.ImeiDAO;
import repository.ManHinhDAO;
import repository.MauSacDAO;
import repository.PinDAO;
import repository.ProductDAO;
import repository.ProductDetailsDAO;
import repository.RAMDAO;
import repository.ROMDAO;
import repository.ThuongHieuDAO;

/**
 *
 * @author tuantq148
 */
public class Product_Panel extends javax.swing.JPanel {

    private ProductDAO productDAO = new ProductDAO();
    private ProductDetailsDAO productDetailsDAO = new ProductDetailsDAO();

    private int index = -1;

    public Product_Panel() {
        initComponents();
        fillTable(productDAO.getProductTable());
        loadComboBox(cboCpu, new CPUDAO().getName());
        loadComboBox(cboPin, new PinDAO().getName());
        loadComboBox(cboRam, new RAMDAO().getName());
        loadComboBox(cboManHinh, new ManHinhDAO().getName());
        loadComboBox(cboRom, new ROMDAO().getName());
        loadComboBox(cboThuongHieu, new ThuongHieuDAO().getName());
        loadComboBox(cboMauSac, new MauSacDAO().getName());
    }

    public void fillTable(List<Object> list) {
        DefaultTableModel tableModel = (DefaultTableModel) tbSanPham.getModel();
        tableModel.setRowCount(0);
        list.forEach(i -> tableModel.addRow((Object[]) i));
        tableModel.fireTableDataChanged();
    }

    public <T> void loadComboBox(JComboBox<T> comboBox, List<String> values) {
        DefaultComboBoxModel<T> boxModel = (DefaultComboBoxModel<T>) comboBox.getModel();
        boxModel.removeAllElements();
        for (String value : values) {
            boxModel.addElement((T) value);
        }
    }

    public void reset() {
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtGiaBan.setText("");
        txtSoLuong.setText("");
        txtIMEI.setText("");

        cboCpu.setSelectedIndex(0);
        cboManHinh.setSelectedIndex(0);
        cboPin.setSelectedIndex(0);
        cboRam.setSelectedIndex(0);
        cboRom.setSelectedIndex(0);
        cboMauSac.setSelectedIndex(0);
        cboCpu.setSelectedIndex(0);
        tbSanPham.clearSelection();
        index = -1;
    }

    public boolean validateForm() {

        if (txtTenSP.getText().trim().isEmpty() || txtGiaBan.getText().trim().isEmpty() || txtSoLuong.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin", "Lỗi", 2);
            return false;
        }

        try {
            Double.valueOf(txtGiaBan.getText().trim());
            Integer.valueOf(txtSoLuong.getText().trim());
        } catch (NumberFormatException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sai định dạng giá và số lượng", "Lỗi", 2);
            return false;
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi", "Lỗi", 2);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        pnlDanhSach = new javax.swing.JPanel();
        pnlThongTinChung = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        pnlCapNhat = new javax.swing.JPanel();
        lblMaSP = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        lblDGB = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        cboThuongHieu = new javax.swing.JComboBox<>();
        txtIMEI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        lblSoLuong1 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        lblSoLuong2 = new javax.swing.JLabel();
        cboPin = new javax.swing.JComboBox<>();
        cboRam = new javax.swing.JComboBox<>();
        cboManHinh = new javax.swing.JComboBox<>();
        cboRom = new javax.swing.JComboBox<>();
        cboMauSac = new javax.swing.JComboBox<>();
        cboCpu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addRAM = new javax.swing.JButton();
        addPin1 = new javax.swing.JButton();
        addRom = new javax.swing.JButton();
        addCpu = new javax.swing.JButton();
        addManHinh = new javax.swing.JButton();
        addMauSac = new javax.swing.JButton();
        addThuongHieu = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(30, 55, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("QUẢN LÍ SẢN PHẨM");

        pnlDanhSach.setBackground(new java.awt.Color(255, 255, 255));

        pnlThongTinChung.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTinChung.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"));

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Pin", "Màn hình", "CPU", "RAM", "ROM", "Màu", "Giá", "Số lượng"
            }
        ));
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbSanPhamMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tbSanPham);

        javax.swing.GroupLayout pnlThongTinChungLayout = new javax.swing.GroupLayout(pnlThongTinChung);
        pnlThongTinChung.setLayout(pnlThongTinChungLayout);
        pnlThongTinChungLayout.setHorizontalGroup(
            pnlThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinChungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE))
        );
        pnlThongTinChungLayout.setVerticalGroup(
            pnlThongTinChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinChungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDanhSachLayout = new javax.swing.GroupLayout(pnlDanhSach);
        pnlDanhSach.setLayout(pnlDanhSachLayout);
        pnlDanhSachLayout.setHorizontalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlThongTinChung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDanhSachLayout.setVerticalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTinChung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlThongTinChung.getAccessibleContext().setAccessibleName("Thông tin chung\n");

        tab.addTab("SẢN PHẨM", pnlDanhSach);

        pnlCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        pnlCapNhat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMaSP.setText("Mã sản phẩm :");

        lblTenSP.setText("Tên sản phẩm :");

        lblDGB.setText("Imei : ");

        txtMaSP.setEditable(false);
        txtMaSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtMaSP.setForeground(new java.awt.Color(255, 0, 0));

        lblSoLuong.setText("Giá bán :");

        lblGhiChu.setText("Mô tả :");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        btnThem.setBackground(new java.awt.Color(246, 185, 59));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(30, 55, 153));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/them.png"))); // NOI18N
        btnThem.setText("Save");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(246, 185, 59));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(30, 55, 153));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/sua.png"))); // NOI18N
        btnSua.setText("Edit");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(246, 185, 59));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(30, 55, 153));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/delete-button.png"))); // NOI18N
        btnXoa.setText("Delete");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setBackground(new java.awt.Color(246, 185, 59));
        btnMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(30, 55, 153));
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/newww.png"))); // NOI18N
        btnMoi.setText("New");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        cboThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iphone", "Samsung", "Nokia", "Xiaomi", "Huawei", "Oppo" }));
        cboThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThuongHieuActionPerformed(evt);
            }
        });

        txtIMEI.setEditable(false);
        txtIMEI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIMEIKeyReleased(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Vui lòng nhập đầy đủ thông tin sản phẩm");

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("trước khi lưu");

        txtTenSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTenSP.setForeground(new java.awt.Color(255, 0, 0));

        txtGiaBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaBanKeyReleased(evt);
            }
        });

        lblSoLuong1.setText("Thương hiệu : ");

        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyReleased(evt);
            }
        });

        lblSoLuong2.setText("Số lượng : ");

        cboPin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboRam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRamActionPerformed(evt);
            }
        });

        cboManHinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboRom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboCpu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Pin");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("CPU");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Màu sắc");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Màn hình");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("RAM");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("ROM");

        addRAM.setBackground(new java.awt.Color(255, 204, 0));
        addRAM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addRAM.setText("+");
        addRAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRAMActionPerformed(evt);
            }
        });

        addPin1.setBackground(new java.awt.Color(255, 204, 0));
        addPin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addPin1.setText("+");
        addPin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPin1ActionPerformed(evt);
            }
        });

        addRom.setBackground(new java.awt.Color(255, 204, 0));
        addRom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addRom.setText("+");
        addRom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRomActionPerformed(evt);
            }
        });

        addCpu.setBackground(new java.awt.Color(255, 204, 0));
        addCpu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addCpu.setText("+");
        addCpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCpuActionPerformed(evt);
            }
        });

        addManHinh.setBackground(new java.awt.Color(255, 204, 0));
        addManHinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addManHinh.setText("+");
        addManHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManHinhActionPerformed(evt);
            }
        });

        addMauSac.setBackground(new java.awt.Color(255, 204, 0));
        addMauSac.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addMauSac.setText("+");
        addMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMauSacActionPerformed(evt);
            }
        });

        addThuongHieu.setBackground(new java.awt.Color(255, 204, 0));
        addThuongHieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addThuongHieu.setText("+");
        addThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addThuongHieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCapNhatLayout = new javax.swing.GroupLayout(pnlCapNhat);
        pnlCapNhat.setLayout(pnlCapNhatLayout);
        pnlCapNhatLayout.setHorizontalGroup(
            pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCapNhatLayout.createSequentialGroup()
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboPin, 0, 178, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboRam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addPin1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboManHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboRom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addManHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(addRom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCapNhatLayout.createSequentialGroup()
                                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlCapNhatLayout.createSequentialGroup()
                                        .addComponent(cboCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCapNhatLayout.createSequentialGroup()
                                .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(pnlCapNhatLayout.createSequentialGroup()
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIMEI, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDGB, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                                                .addComponent(cboThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(addThuongHieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(lblSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(115, 115, 115)
                                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCapNhatLayout.createSequentialGroup()
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );
        pnlCapNhatLayout.setVerticalGroup(
            pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCapNhatLayout.createSequentialGroup()
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                                .addComponent(lblMaSP)
                                .addGap(5, 5, 5)
                                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(lblDGB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIMEI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lblSoLuong1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addThuongHieu))
                                .addGap(24, 24, 24)
                                .addComponent(lblSoLuong2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                                .addComponent(lblTenSP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSoLuong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGhiChu)
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboPin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboManHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addManHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addPin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboRom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addRom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboRam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addRAM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(pnlCapNhatLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnSua))
                        .addGap(18, 18, 18)
                        .addComponent(btnMoi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1171, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(pnlCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        tab.addTab("CHI TIẾT SẢN PHẨM", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked

    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void cboRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRamActionPerformed

    private void txtSoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongKeyReleased

    private void txtGiaBanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaBanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaBanKeyReleased

    private void txtIMEIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIMEIKeyReleased

    }//GEN-LAST:event_txtIMEIKeyReleased

    private void cboThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThuongHieuActionPerformed

    }//GEN-LAST:event_cboThuongHieuActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        reset();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (index != -1 && index < productDAO.getProductTable().size()) {
            Object[] data = (Object[]) productDAO.getProductTable().get(index);

            Product product = productDAO.getById(Integer.valueOf(data[9].toString()));
            ProductDetails productDetail = productDetailsDAO.getByidSanPham(product.getId()).get(0);
            productDetailsDAO.delete(productDetail.getId());
            productDAO.delete(product.getId());
            new ImeiDAO().delete(productDetail.getIdIMEI());

            fillTable(productDAO.getProductTable());
            reset();
            tab.setSelectedIndex(0);
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Hãy chọn dòng muốn xóa", "Delete", 2);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (index != -1) {
            if (validateForm()) {
                Object[] data = (Object[]) productDAO.getProductTable().get(index);
                Product product = productDAO.getById(Integer.valueOf(data[9].toString()));
                ProductDetails productDetail = productDetailsDAO.getByidSanPham(product.getId()).get(0);

                product.setTen(txtTenSP.getText().trim());
                product.setSoLuong(Integer.valueOf(txtSoLuong.getText().trim()));
                if (productDAO.insert(product)) {
                    productDetail.setGia(Double.valueOf(txtGiaBan.getText().trim()));
                    productDetail.setIdThuongHieu(new ThuongHieuDAO().getByName(cboThuongHieu.getSelectedItem().toString()).getId());
                    productDetail.setIdPin(new PinDAO().getByName(cboPin.getSelectedItem().toString()).getId());
                    productDetail.setIdCPU(new CPUDAO().getByName(cboCpu.getSelectedItem().toString()).getId());
                    productDetail.setIdManHinh(new ManHinhDAO().getByName(cboManHinh.getSelectedItem().toString()).getId());
                    productDetail.setIdRAM(new RAMDAO().getByName(cboRam.getSelectedItem().toString()).getId());
                    productDetail.setIdROM(new ROMDAO().getByName(cboRom.getSelectedItem().toString()).getId());
                    productDetail.setIdMau(new MauSacDAO().getByName(cboMauSac.getSelectedItem().toString()).getId());
                    productDetailsDAO.update(productDetail);

                    JOptionPane.showMessageDialog(this, "Edit thành công");
                    fillTable(productDAO.getProductTable());
                    reset();
                    tab.setSelectedIndex(0);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hãy chọn dòng muốn sửa", "Update", 2);
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (validateForm()) {
            for (Product i : productDAO.getAll()) {
                if (i.getTen().trim().toLowerCase().equals(txtTenSP.getText().trim().toLowerCase())) {
                    JOptionPane.showMessageDialog(this, "Sản phẩm đã tồn tại", "Lỗi", 2);
                    return;
                }
            }
            Product product = new Product();
            ProductDetails productDetail = new ProductDetails();
            Imei1 imei = new Imei1();
            imei.setTen(productDAO.generateIMEI());
            new ImeiDAO().insert(imei);

            product.setTen(txtTenSP.getText().trim());
            product.setSoLuong(Integer.valueOf(txtSoLuong.getText().trim()));
            if (productDAO.insert(product)) {
                productDetail.setGia(Double.valueOf(txtGiaBan.getText().trim()));
                productDetail.setIdSanPham(productDAO.getByName(txtTenSP.getText().trim()).getId());
                productDetail.setIdIMEI(new ImeiDAO().getByName(imei.getTen()).getId());
                productDetail.setIdThuongHieu(new ThuongHieuDAO().getByName(cboThuongHieu.getSelectedItem().toString()).getId());
                productDetail.setIdPin(new PinDAO().getByName(cboPin.getSelectedItem().toString()).getId());
                productDetail.setIdCPU(new CPUDAO().getByName(cboCpu.getSelectedItem().toString()).getId());
                productDetail.setIdManHinh(new ManHinhDAO().getByName(cboManHinh.getSelectedItem().toString()).getId());
                productDetail.setIdRAM(new RAMDAO().getByName(cboRam.getSelectedItem().toString()).getId());
                productDetail.setIdROM(new ROMDAO().getByName(cboRom.getSelectedItem().toString()).getId());
                productDetail.setIdMau(new MauSacDAO().getByName(cboMauSac.getSelectedItem().toString()).getId());
                productDetailsDAO.insert(productDetail);

                fillTable(productDAO.getProductTable());
                reset();
                tab.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tbSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMousePressed
        index = tbSanPham.getSelectedRow();
        if (index < 0 || index >= productDAO.getProductTable().size()) {
            JOptionPane.showMessageDialog(this, "Lỗi rồi ");
        }
        if (index != -1 && evt.getClickCount() == 2) {
            Object[] product = (Object[]) productDAO.getProductTable().get(index);

            txtMaSP.setText(product[9].toString());
            txtTenSP.setText(product[0].toString());
            txtGiaBan.setText(product[7].toString());
            txtSoLuong.setText(product[8].toString());
            txtIMEI.setText(product[11].toString());

            cboCpu.setSelectedItem(product[3].toString());
            cboManHinh.setSelectedItem(product[2].toString());
            cboPin.setSelectedItem(product[1].toString());
            cboRam.setSelectedItem(product[4].toString());
            cboRom.setSelectedItem(product[5].toString());
            cboMauSac.setSelectedItem(product[6].toString());
            cboThuongHieu.setSelectedItem(product[12].toString());
            tab.setSelectedIndex(1);
        }
    }//GEN-LAST:event_tbSanPhamMousePressed

    private void addRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRAMActionPerformed
        String ram = JOptionPane.showInputDialog("Thêm loại RAM mới");
        if (ram != null && !ram.trim().isEmpty()) {
            new RAMDAO().insert(ram);
            loadComboBox(cboRam, new RAMDAO().getName());
        }
    }//GEN-LAST:event_addRAMActionPerformed

    private void addPin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPin1ActionPerformed

        String pin = JOptionPane.showInputDialog("Thêm loại PIN mới");
        if (pin != null && !pin.trim().isEmpty()) {
            new PinDAO().insert(pin);
            loadComboBox(cboPin, new PinDAO().getName());
        }
    }//GEN-LAST:event_addPin1ActionPerformed

    private void addRomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRomActionPerformed
        String rom = JOptionPane.showInputDialog("Thêm loại ROM mới");
        if (rom != null && !rom.trim().isEmpty()) {
            new ROMDAO().insert(rom);
            loadComboBox(cboRom, new ROMDAO().getName());
        }
    }//GEN-LAST:event_addRomActionPerformed

    private void addCpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCpuActionPerformed
        String cpu = JOptionPane.showInputDialog("Thêm loại CPU mới");
        if (cpu != null && !cpu.trim().isEmpty()) {
            new CPUDAO().insert(cpu);
            loadComboBox(cboCpu, new CPUDAO().getName());
        }
    }//GEN-LAST:event_addCpuActionPerformed

    private void addManHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManHinhActionPerformed
        String man = JOptionPane.showInputDialog("Thêm loại Màn hình mới");
        if (man != null && !man.trim().isEmpty()) {
            new ManHinhDAO().insert(man);
            loadComboBox(cboManHinh, new ManHinhDAO().getName());
        }
    }//GEN-LAST:event_addManHinhActionPerformed

    private void addMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMauSacActionPerformed
        String mau = JOptionPane.showInputDialog("Thêm loại màu mới");
        if (mau != null && !mau.trim().isEmpty()) {
            new MauSacDAO().insert(mau);
            loadComboBox(cboMauSac, new MauSacDAO().getName());
        }
    }//GEN-LAST:event_addMauSacActionPerformed

    private void addThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addThuongHieuActionPerformed
        String th = JOptionPane.showInputDialog("Thêm loại thương hiệu mới");
        if (th != null && !th.trim().isEmpty()) {
            ThuongHieuDAO thuongHieuDAO = new ThuongHieuDAO();
            thuongHieuDAO.insert(th);
            loadComboBox(cboThuongHieu, thuongHieuDAO.getName());
        }
    }//GEN-LAST:event_addThuongHieuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCpu;
    private javax.swing.JButton addManHinh;
    private javax.swing.JButton addMauSac;
    private javax.swing.JButton addPin1;
    private javax.swing.JButton addRAM;
    private javax.swing.JButton addRom;
    private javax.swing.JButton addThuongHieu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboCpu;
    private javax.swing.JComboBox<String> cboManHinh;
    private javax.swing.JComboBox<String> cboMauSac;
    private javax.swing.JComboBox<String> cboPin;
    private javax.swing.JComboBox<String> cboRam;
    private javax.swing.JComboBox<String> cboRom;
    private javax.swing.JComboBox<String> cboThuongHieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDGB;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblSoLuong1;
    private javax.swing.JLabel lblSoLuong2;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlCapNhat;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JPanel pnlThongTinChung;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtIMEI;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
